# Generated by Django 4.1.3 on 2022-11-29 21:23

from django.db import migrations, models
import django.db.models.deletion
import laser.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firstname",
                    models.CharField(max_length=150, verbose_name="First name"),
                ),
                (
                    "lastname",
                    models.CharField(max_length=150, verbose_name="Last name"),
                ),
                (
                    "birthday",
                    models.DateField(blank=True, null=True, verbose_name="Birthday"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Clients",
                "verbose_name_plural": "Clients",
            },
        ),
        migrations.CreateModel(
            name="Tatto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Name tatto")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=laser.models.tatto_photo_path
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="laser.clients"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tatto",
                "verbose_name_plural": "Tatto",
            },
        ),
        migrations.CreateModel(
            name="Sessions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datetime_session",
                    models.DateTimeField(verbose_name="Date and time session"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Активна"),
                            ("CLOSED", "Закрыта"),
                            ("NOT_COMED", "Не пришёл"),
                        ],
                        default="ACTIVE",
                        max_length=200,
                        verbose_name="Status",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="laser.clients"
                    ),
                ),
                ("tatto_list", models.ManyToManyField(to="laser.tatto")),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
            },
        ),
        migrations.CreateModel(
            name="Photos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "before_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=laser.models.tatto_photo_path,
                        verbose_name="Before photo",
                    ),
                ),
                (
                    "after_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=laser.models.tatto_photo_path,
                        verbose_name="After photo",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="laser.sessions"
                    ),
                ),
                (
                    "tatto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="laser.tatto"
                    ),
                ),
            ],
            options={
                "verbose_name": "Photos",
                "verbose_name_plural": "Photos",
            },
        ),
    ]
